### ISSUE TITLE
How do I apply traffic items ( Traffic.Apply() ) in a non-blocking way?

### ISSUE THREAD

**Issue by abindhar** [OpenIxia/ixnetwork_restpy#12]
I am using ixNetwork.Traffic.Apply(). 
I'm looking to apply this in a non-blocking way. At present, it blocks until the items are applied.

**Comment by ajbalogh** [comment]
At this time there is no async Traffic.Apply operation offered by the IxNetwork server.

The ixnetwork_restpy library will continue to poll the server until the poll of the Apply operation returns one of these states:  SUCCESS | ERROR | EXCEPTION.

Even if you changed the library to bypass the polling and issue another REST command the server will return an API CONTENTION error if the Apply operation has not completed with one of the above states.
