### ISSUE TITLE
invalid method name (None)

### ISSUE THREAD

**Issue by pwlodawi** [OpenIxia/ixnetwork_restpy#16]
Invalid method name None in 
ixnetwork_restpy\testplatform\sessions\ixnetwork\vport\protocols\queueproperty_3j0uxvldwvzl3f1zxvluhjvcgvydhk.py", line 50

**Comment by ajbalogh** [comment]
Fixed.

**Comment by ajbalogh** [comment]
This will be available in 1.0.45
