### ISSUE TITLE
invalid docstring

### ISSUE THREAD

**Issue by pwlodawi** [OpenIxia/ixnetwork_restpy#17]
Docstring starting at line 171 of 
ixnetwork_restpy/testplatform/sessions/ixnetwork/vport/protocols/router_byb3rvy29scy9vc3bmvjmvcm91dgvy.py is invalid

It should be raw string or not use backslash character.

**Comment by pwlodawi** [comment]
It applies to all docstrings that include phrase "Reload\Upgrade"

**Comment by ajbalogh** [comment]
This will be addressed in version 1.0.46
