### ISSUE TITLE
AresOne - how to configure 100G port using Alignment marker type = 100GBASE-*R2

### ISSUE THREAD

**Issue by priteshjmodi** [OpenIxia/ixnetwork_restpy#19]
When using IxExplorer I can see the option to configure alignment marker type. 
![image](https://user-images.githubusercontent.com/48070109/70458779-ab881f80-1a67-11ea-977f-164afca28969.png)

But, when when I allocate this port using IxNetwork.AssignPort(), alignment marker default backs to 100GBASE-*R4. Is there a method to set alignment markers correctly for 100G speed?

**Comment by ajbalogh** [comment]
The alignmentMarker property hasn't yet been exposed in any API.  
I've confirmed with the engineering team responsible for layer 1 config that the property will be available by Q2 2020.

**Comment by priteshjmodi** [comment]
Hi @ajbalogh , Thanks for your response. I would appreciate if engineering team can prioritize this development sooner.

**Comment by ajbalogh** [comment]
@whandjr  just wanted ensure you are aware of this issue.

**Comment by ajbalogh** [comment]
Implemented in IxNetwork 9.10 and exposed as part of ixnetwork-restpy 1.0.58
