### ISSUE TITLE
Novus 100g IeeeL1Defaults settings with IxOS 9.00.1900.10 version

### ISSUE THREAD

**Issue by priteshjmodi** [OpenIxia/ixnetwork_restpy#20]
Hi,

I am using below function to set IeeL1Defaults on Novus 100G / 25G port speed. But after updating to Active IxOS Version         : 9.00.1900.10  , I see ports come up with IEEE/Consortion defaults enabled. 

Is there any additional configuration required to turn off IEEE L1 defaults and AN to disable?

----
![image](https://user-images.githubusercontent.com/48070109/71756804-a3dd5000-2e46-11ea-9adb-c9afb2a8d9f6.png)

----
        self.vports_obj[vport_name].L1Config.NovusHundredGigLan.IeeeL1Defaults = False
        if an == "off":
            self.vports_obj[vport_name].L1Config.NovusHundredGigLan.EnableAutoNegotiation = False
        if fec_mode == "off":
            self.vports_obj[vport_name].L1Config.NovusHundredGigLan.EnableRsFec = False

self.vports_obj[vport_name].L1Config.NovusHundredGigLan.IeeeL1Defaults = False

**Comment by ajbalogh** [comment]
That should be sufficient but I would recommend using the update() method.

```
self.vports_obj[vport_name].L1Config.NovusHundredGigLan.update(IeeeL1Defaults=False, EnableAutoNegotiation=False, EnableRsFec=False)
```
