### ISSUE TITLE
Update method on NovusHundredGigLan Auto Neg feature does not work on IxOS ver > 9.00

### ISSUE THREAD

**Issue by priteshjmodi** [OpenIxia/ixnetwork_restpy#22]
Hello,

when i use update method for setting Auto Neg (shown in commented out code below), port does not  set Auto Neg = False. This is with IxOS 9.00 patch2 and Novus Hundred Gig cards. I had to use direct assignment and that works correctly. 

-----
    def set_port_an(self, vport_name, an="off"):
        '''
           method to set autoneg mode based on portname
           vport: <string> port name
           an: <string> off (default) | on

        if an == "off":
            self.vports_obj[vport_name].L1Config.NovusHundredGigLan.update(IeeeL1Defaults=False, EnableAutoNegotiation=False)
        else:
            self.vports_obj[vport_name].L1Config.NovusHundredGigLan.update(IeeeL1Defaults=True, EnableAutoNegotiation=True)
        '''
        self.vports_obj[vport_name].L1Config.NovusHundredGigLan.IeeeL1Defaults = False
        if an == "off":
            self.vports_obj[vport_name].L1Config.NovusHundredGigLan.EnableAutoNegotiation = False
        else:
            self.vports_obj[vport_name].L1Config.NovusHundredGigLan.EnableAutoNegotiation = True

----

**Comment by priteshjmodi** [comment]
@rbandanapudi@barefootnetworks.com .. fyi

**Comment by ajbalogh** [comment]
This is a bug with the NovusHundredGigLan API publisher in the IxNetwork API Server not with the ixnetwork_restpy package.
An internal bug has been opened and the fix will be part of IxNetwork API Server 9.10.

**Comment by priteshjmodi** [comment]
thanks for confirming.

**Comment by ajbalogh** [comment]
Thank you for raising the issue and providing the workaround.
