### ISSUE TITLE
AresOne - how to disable AutoInstrumentation ? 

### ISSUE THREAD

**Issue by priteshjmodi** [OpenIxia/ixnetwork_restpy#23]
Hi there,

I am trying to completely disable auto instrumentation on a traffic item. 
In the IxExplorer GUI, I can see the option and remove it.  Please let me know how to completely disable AutoInstrumentation from scripts.

![image](https://user-images.githubusercontent.com/48070109/77243366-7b9ffa80-6bc6-11ea-8387-a149c821b356.png)

But when I try to setup this via restpy script using below option, it does not work. 
 
 /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:794: ------------------------------------------

              self.vports_obj[vport_name].L1Config.AresOneFourHundredGigLan.AutoInstrumentation = 'endOfFrame'
                File "/usr/local/lib/python2.7/dist-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/vport/l1config/aresonefourhundredgiglan/aresonefourhundredgiglan.py", line 47, in AutoInstrumentation
                    self._set_attribute('autoInstrumentation', value)
                      File "/usr/local/lib/python2.7/dist-packages/ixnetwork_restpy/base.py", line 141, in _set_attribute
                          raise e
                          BadRequestError: Port does not support 'endOfFrame'

**Comment by ajbalogh** [comment]
Remove all traffic item tracking to disable instrumentation.

![image](https://user-images.githubusercontent.com/30300566/77253866-9f8d2b80-6c1a-11ea-9b96-9fdf78f6b130.png)

from ixnetwork_restpy import SessionAssistant


session_assistant = SessionAssistant(IpAddress='127.0.0.1', RestPort=11009, ClearConfig=True)
vport1 = session_assistant.Ixnetwork.Vport.add()
vport2 = session_assistant.Ixnetwork.Vport.add()
traffic1 = session_assistant.Ixnetwork.Traffic.TrafficItem.add(TrafficType='raw')
traffic1.EndpointSet.add(Sources=vport1.Protocols.find(), Destinations=vport2.Protocols.find())
tracking = traffic1.Tracking.find()
tracking.TrackBy = []

**Comment by priteshjmodi** [comment]
Thank you! It works.
