### ISSUE TITLE
How to reset CSV logging results file ?

### ISSUE THREAD

**Issue by pwlodawi** [OpenIxia/ixnetwork_restpy#36]
I use CsvLogging to save traffic item trace. It works fine but for the first traffic run only.

When I start traffic again and enable logging results seems to be appended to results file. 
The result is csv file fomated like this:
```
<headers row>
<first run data rows>
<headers row>
<second run data rows>
```

Is it expected behavior ? Is there any way to reset csv file between traffic runs ?

**Comment by therkong** [comment]
The <headers row> is added when you enableCsvLogging to True.   If you comment out disabling and enabling of the csvLogging on the 2nd run, then there’s no <hearders row> on the second run.   

There's one CSV file for a session.  Unless you reopen IxNetwork session, it keeps writing into the same file.
