### ISSUE TITLE
Session.GetFileList fails when passed a remote_directory

### ISSUE THREAD

**Issue by rfrye-github** [OpenIxia/ixnetwork_restpy#37]
testplatform/sessions/sessions.py, class Session, method GetFileList(self, remote_directory=None)
Line 325:
href = '%s?absolute=%s'

should be:
href = '%s?absolute=%s' % (href, remote_directory)

**Comment by ajbalogh** [comment]
thanks for raising this issue - the fix will be available in version 1.0.60
