### ISSUE TITLE
ISIS level type changing

### ISSUE THREAD

**Issue by skayres** [OpenIxia/ixnetwork_restpy#6]
Hi!

Couldn't you provide the sample how to change 'Level Type' attribute for an isis router? 
I didn't found this attribute via API browser and in isis*.py classes of ixnetwork_restpy.

Thank you!

**Comment by ajbalogh** [comment]
All the level settings are configured under the isis interface, not the router.
The following is some code that shows where in the hierarchy the LevelType can be found.

```
from ixnetwork_restpy.testplatform.testplatform import TestPlatform


testplatform = TestPlatform('127.0.0.1')
sessions = testplatform.Sessions.add()
ixnetwork = sessions.Ixnetwork
topology = ixnetwork.Topology.add()
ethernet = devicegroup.Ethernet.add()
isisl3 = ethernet.IsisL3.add()
leveltype = isisl3.LevelType
testplatform.info(leveltype)
```

**Comment by skayres** [comment]
Yes, by this way I can get access to LevelType for read. But how to set attribute 'LevelType' ?

```
print('Isis level type:')
print (isis_1.LevelType)

isis_1.LevelType='level1'
```

```
Isis level type:
level2
Traceback (most recent call last):
  File "ixia_isis_setup_rest.py", line 117, in <module>
    isis_1.LevelType='level1'
AttributeError: can't set attribute
```

The same question about 'EnableWideMetric' atribute of IsisL3Router class.

**Comment by skayres** [comment]
Sorry my dummy questions.

`isis_1.LevelType.Single('level1')`
