### ISSUE TITLE
Issue with updating traffic item attributes with RestPy

### ISSUE THREAD

**Issue by desaimg1** [OpenIxia/ixnetwork_restpy#61]
facing issue with updating traffic items with latest version of RestPy

We have wrapper written  for modifying traffic attributes. It was working fine before but failing now.

API :
    def configPacketHeaderField(self, stackIdObj, fieldName, data):
        """
        Desciption
            Configure raw packets in a Traffic Item.
            In order to know the field names to modify, use showPacketHeaderFieldNames() to
            display the names:

        fieldName: The field name in the packet header to modify.
                   Example. In a MPLS packet header, the fields would be "Label value",
                   "MPLS Exp", etc.
                   Note: Use showPacketHeaderFieldNames(stackObj) API to dispaly your options.

        data: Example:
             data={'valueType': 'valueList',
                   'valueList': ['1001', '1002'],
                   auto': False}
             data={'valueType': 'increment',
                   'startValue': '1.1.1.1',
                   'stepValue': '0.0.0.1',
                   'countValue': 2}
             data={'valueType': 'increment',
                   'startValue': '00:01:01:01:00:01',
                   'stepValue': '00:00:00:00:00:01'}
             data={'valueType': 'increment',
                   'startValue': 1001,
                   'stepValue': 1,
                   'countValue': 2,
                   'auto': False}

        Example: To modify MPLS field:
            packetHeaderObj = trafficObj.getTrafficItemPktHeaderStackObj(
                trafficItemName='Raw MPLS/UDP',
                packetHeaderName='mpls')
            trafficObj.configPacketHeaderField(packetHeaderObj,
                                               fieldName='MPLS Exp',
                                               data={'valueType': 'increment',
                                               'startValue': '4',
                                               'stepValue': '1',
                                               'countValue': 1,
                                               'auto': False})
        """
        fieldId = None
        fieldObj = None
        stackFieldObj = stackIdObj.Field.find()
        for (index, eachFieldId) in enumerate(stackFieldObj):
            if bool(re.match(fieldName, eachFieldId.DisplayName, re.I)):
                fieldId = index + 1
                fieldObj = eachFieldId
                break
        if fieldId is None:
            raise IxNetRestApiException('Failed to located your provided fieldName:', fieldName)
        self.ixnObj.logInfo('configPacketHeaderFieldId:  fieldIdObj: %s' % stackIdObj.href +
                            '/field/' + str(fieldId), timestamp=False)
        import pdb;
        pdb.set_trace()
        newdict={}
        for k, v in data.items():
            newdict.update({k[0:1].capitalize() + k[1:]: v})

        fieldObj.update(ValueType=data.get('valueType'), )
        if data.get('valueType'):
            fieldObj.ValueType = data.get('valueType')
        else:
            fieldObj.ValueType = 'singleValue'
            data['valueType'] = 'singleValue'
        if data.get('auto'):
            fieldObj.Auto = data['auto']
        if data.get('valueType') == 'singleValue':
            fieldObj.SingleValue = data['fieldValue'] if data.get('fieldValue') else 0
        elif data.get('valueType') in ['increment', 'decrement']:
            for item, value in data.items():
                if item in ['startValue', 'stepValue', 'countValue']:
                    itemObj = item[0:1].capitalize() + item[1:]
                    setattr(fieldObj, itemObj, value)
        elif data.get('valueType') == 'valueList':
            if data.get('valueList'):
                fieldObj.ValueList = data['valueList']
        elif data.get('valueType') == 'random':
            for item, value in data.items():
                if item in ['countValue', 'seed', 'randomMask', 'fixedBits']:
                    itemObj = item[0:1].capitalize() + item[1:]
                    setattr(fieldObj, itemObj, value)
        elif data.get('valueType') == 'repeatableRandomRange':
            for item, value in data.items():
                if item in ['countValue', 'seed', 'stepValue', 'maxValue', 'minValue']:
                    itemObj = item[0:1].capitalize() + item[1:]
                    setattr(fieldObj, itemObj, value)
        elif data.get('valueType') == 'nonRepeatableRandom':
            for item, value in data.items():
                if item in ['randomMask', 'fixedBits']:
                    itemObj = item[0:1].capitalize() + item[1:]
                    setattr(fieldObj, itemObj, value)

API call:

    trafObj2 = trafficStatus[0]
    endpointObj2 = trafficStatus[1][0]
    configElementObj2 = trafficStatus[2][0]

    stackObj = ixn_obj.trafficObj.getPacketHeaderStackIdObj(configElementObj2, stackId=1)
    ixn_obj.trafficObj.configPacketHeaderField(stackObj,
                                       fieldName='Destination MAC Address',
                                       data={'valueType': 'increment',
                                             'startValue': mac2,
                                             'stepValue': '00:00:00:00:00:01',
                                             'countValue': len(vlanList)})

Output:

1: Ethernet II
configPacketHeaderFieldId:  fieldIdObj: /api/v1/sessions/109/ixnetwork/traffic/trafficItem/1/configElement/1/stack/1/field/1

(Pdb) fieldObj
<ixnetwork_restpy.testplatform.sessions.ixnetwork.traffic.trafficitem.configelement.stack.field.field.Field object at 0x000001DD75DB15E0>

(Pdb) fieldObj.update(ValueType='increment', StartValue= '00:02:02:00:00:02', StepValue= '00:00:00:00:00:01', CountValue= 18)
*** ixnetwork_restpy.errors.BadRequestError: InstanceId is not a string
System.Exception: InstanceId is not a string
   at SDMCsLib.SDMObjIdPiece.GetIdAsString()
   at IxNetwork.Traffic2.Publishers.StackFieldHandler.Find(EnterExitSingleObjectHandler_EnterArgs args)
   at SDMHelpers.WalkContext.walkTo(SDMObjId objid, Hashtable idMapResponse, EnterReason reason)
   at SDMHelpers.SimplePublisher.Commit(ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitMessages, SDMSandbox track)
   at SDMCsLib.SDMPeer.commitPiece(ArrayList deltasForPublisher, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUnique)
   at SDMCsLib.SDMPeer.SANDBOX_DoCommit(Int32 eventMatch, ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUni
que, eSandboxType sandboxType)
   at SDMCsLib.SDMSandbox.DoCommit(Boolean bCommitIfUnique, eSandboxType sandboxType)
   at SDMCsLib.RestService.SdmSandbox.Commit(Boolean isAddOperation)
   at SDMCsLib.RestService.SdmObject.Patch()
   at SDMCsLib.RestService.V1ObjectController.Patch(String path)
        Current Server Errors/Warnings:
        01/23/2022 23:16:15 [WARNING] [Traffic Generate required] The Traffic Item was modified. Please perform a Traffic Generate to update the associated traffic Flow Groups
(Pdb)

   one more method as per example code :

   (Pdb) dest_mac=stackIdObj.Field.find(FieldTypeId='ethernet.header.destinationAddress')

(Pdb) dest_mac.update(ValueType='increment', StartValue= '00:02:02:00:00:02', StepValue= '00:00:00:00:00:01', CountValue= 18)
*** ixnetwork_restpy.errors.BadRequestError: InstanceId is not a string
System.Exception: InstanceId is not a string
   at SDMCsLib.SDMObjIdPiece.GetIdAsString()
   at IxNetwork.Traffic2.Publishers.StackFieldHandler.Find(EnterExitSingleObjectHandler_EnterArgs args)
   at SDMHelpers.WalkContext.walkTo(SDMObjId objid, Hashtable idMapResponse, EnterReason reason)
   at SDMHelpers.SimplePublisher.Commit(ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitMessages, SDMSandbox track)
   at SDMCsLib.SDMPeer.commitPiece(ArrayList deltasForPublisher, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUnique)
   at SDMCsLib.SDMPeer.SANDBOX_DoCommit(Int32 eventMatch, ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUni
que, eSandboxType sandboxType)
   at SDMCsLib.SDMSandbox.DoCommit(Boolean bCommitIfUnique, eSandboxType sandboxType)
   at SDMCsLib.RestService.SdmSandbox.Commit(Boolean isAddOperation)
   at SDMCsLib.RestService.SdmObject.Patch()
   at SDMCsLib.RestService.V1ObjectController.Patch(String path)
        Current Server Errors/Warnings:
        01/23/2022 23:16:15 [WARNING] [Traffic Generate required] The Traffic Item was modified. Please perform a Traffic Generate to update the associated traffic Flow Groups
(Pdb)

**Comment by JensNeumannZAL** [comment]
Hello,

I have the same issue. I also did the same operation with the browser API and found a difference in the JSON string:

This is what the RestPy library sends. Interestingly, the "id" part is not explicitly added by my script but seems to be added internally. Also, contrary to what the server responds (`System.Exception: InstanceId is not a string`), it is actually a string as can be seen here clearly.
`/api/v1/sessions/1/ixnetwork/traffic/trafficItem/1/configElement/1/stack/1/field`
`{"trackingEnabled": true, "valueList": ["00:00:00:00:00:03"], "valueType": "valueList", "id": "1"}`

In the browser API it looks like this
`### API Browser RFC 2616 code snippet
PATCH https://localhost:11009/api/v1/sessions/1/ixnetwork/traffic/trafficItem/1/configElement/1/stack/1/field/1
content-type: text/plain; charset=utf-8

{
	"valueList": [
		"00:00:00:00:00:04"
	],
	"valueType": "valueList"
}`

As you can see, the `id` part does not even appear here.

**Comment by hshakaryan** [comment]
> facing issue with updating traffic items with latest version of RestPy
> 
> We have wrapper written for modifying traffic attributes. It was working fine before but failing now.
> 
> API : def configPacketHeaderField(self, stackIdObj, fieldName, data): """ Desciption Configure raw packets in a Traffic Item. In order to know the field names to modify, use showPacketHeaderFieldNames() to display the names:
> 
> ```
>     fieldName: The field name in the packet header to modify.
>                Example. In a MPLS packet header, the fields would be "Label value",
>                "MPLS Exp", etc.
>                Note: Use showPacketHeaderFieldNames(stackObj) API to dispaly your options.
> 
>     data: Example:
>          data={'valueType': 'valueList',
>                'valueList': ['1001', '1002'],
>                auto': False}
>          data={'valueType': 'increment',
>                'startValue': '1.1.1.1',
>                'stepValue': '0.0.0.1',
>                'countValue': 2}
>          data={'valueType': 'increment',
>                'startValue': '00:01:01:01:00:01',
>                'stepValue': '00:00:00:00:00:01'}
>          data={'valueType': 'increment',
>                'startValue': 1001,
>                'stepValue': 1,
>                'countValue': 2,
>                'auto': False}
> 
>     Example: To modify MPLS field:
>         packetHeaderObj = trafficObj.getTrafficItemPktHeaderStackObj(
>             trafficItemName='Raw MPLS/UDP',
>             packetHeaderName='mpls')
>         trafficObj.configPacketHeaderField(packetHeaderObj,
>                                            fieldName='MPLS Exp',
>                                            data={'valueType': 'increment',
>                                            'startValue': '4',
>                                            'stepValue': '1',
>                                            'countValue': 1,
>                                            'auto': False})
>     """
>     fieldId = None
>     fieldObj = None
>     stackFieldObj = stackIdObj.Field.find()
>     for (index, eachFieldId) in enumerate(stackFieldObj):
>         if bool(re.match(fieldName, eachFieldId.DisplayName, re.I)):
>             fieldId = index + 1
>             fieldObj = eachFieldId
>             break
>     if fieldId is None:
>         raise IxNetRestApiException('Failed to located your provided fieldName:', fieldName)
>     self.ixnObj.logInfo('configPacketHeaderFieldId:  fieldIdObj: %s' % stackIdObj.href +
>                         '/field/' + str(fieldId), timestamp=False)
>     import pdb;
>     pdb.set_trace()
>     newdict={}
>     for k, v in data.items():
>         newdict.update({k[0:1].capitalize() + k[1:]: v})
> 
>     fieldObj.update(ValueType=data.get('valueType'), )
>     if data.get('valueType'):
>         fieldObj.ValueType = data.get('valueType')
>     else:
>         fieldObj.ValueType = 'singleValue'
>         data['valueType'] = 'singleValue'
>     if data.get('auto'):
>         fieldObj.Auto = data['auto']
>     if data.get('valueType') == 'singleValue':
>         fieldObj.SingleValue = data['fieldValue'] if data.get('fieldValue') else 0
>     elif data.get('valueType') in ['increment', 'decrement']:
>         for item, value in data.items():
>             if item in ['startValue', 'stepValue', 'countValue']:
>                 itemObj = item[0:1].capitalize() + item[1:]
>                 setattr(fieldObj, itemObj, value)
>     elif data.get('valueType') == 'valueList':
>         if data.get('valueList'):
>             fieldObj.ValueList = data['valueList']
>     elif data.get('valueType') == 'random':
>         for item, value in data.items():
>             if item in ['countValue', 'seed', 'randomMask', 'fixedBits']:
>                 itemObj = item[0:1].capitalize() + item[1:]
>                 setattr(fieldObj, itemObj, value)
>     elif data.get('valueType') == 'repeatableRandomRange':
>         for item, value in data.items():
>             if item in ['countValue', 'seed', 'stepValue', 'maxValue', 'minValue']:
>                 itemObj = item[0:1].capitalize() + item[1:]
>                 setattr(fieldObj, itemObj, value)
>     elif data.get('valueType') == 'nonRepeatableRandom':
>         for item, value in data.items():
>             if item in ['randomMask', 'fixedBits']:
>                 itemObj = item[0:1].capitalize() + item[1:]
>                 setattr(fieldObj, itemObj, value)
> ```
> 
> API call:
> 
> ```
> trafObj2 = trafficStatus[0]
> endpointObj2 = trafficStatus[1][0]
> configElementObj2 = trafficStatus[2][0]
> 
> stackObj = ixn_obj.trafficObj.getPacketHeaderStackIdObj(configElementObj2, stackId=1)
> ixn_obj.trafficObj.configPacketHeaderField(stackObj,
>                                    fieldName='Destination MAC Address',
>                                    data={'valueType': 'increment',
>                                          'startValue': mac2,
>                                          'stepValue': '00:00:00:00:00:01',
>                                          'countValue': len(vlanList)})
> ```
> 
> Output:
> 
> 1: Ethernet II configPacketHeaderFieldId: fieldIdObj: /api/v1/sessions/109/ixnetwork/traffic/trafficItem/1/configElement/1/stack/1/field/1
> 
> (Pdb) fieldObj <ixnetwork_restpy.testplatform.sessions.ixnetwork.traffic.trafficitem.configelement.stack.field.field.Field object at 0x000001DD75DB15E0>
> 
> (Pdb) fieldObj.update(ValueType='increment', StartValue= '00:02:02:00:00:02', StepValue= '00:00:00:00:00:01', CountValue= 18) *** ixnetwork_restpy.errors.BadRequestError: InstanceId is not a string System.Exception: InstanceId is not a string at SDMCsLib.SDMObjIdPiece.GetIdAsString() at IxNetwork.Traffic2.Publishers.StackFieldHandler.Find(EnterExitSingleObjectHandler_EnterArgs args) at SDMHelpers.WalkContext.walkTo(SDMObjId objid, Hashtable idMapResponse, EnterReason reason) at SDMHelpers.SimplePublisher.Commit(ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitMessages, SDMSandbox track) at SDMCsLib.SDMPeer.commitPiece(ArrayList deltasForPublisher, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUnique) at SDMCsLib.SDMPeer.SANDBOX_DoCommit(Int32 eventMatch, ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUni que, eSandboxType sandboxType) at SDMCsLib.SDMSandbox.DoCommit(Boolean bCommitIfUnique, eSandboxType sandboxType) at SDMCsLib.RestService.SdmSandbox.Commit(Boolean isAddOperation) at SDMCsLib.RestService.SdmObject.Patch() at SDMCsLib.RestService.V1ObjectController.Patch(String path) Current Server Errors/Warnings: 01/23/2022 23:16:15 [WARNING] [Traffic Generate required] The Traffic Item was modified. Please perform a Traffic Generate to update the associated traffic Flow Groups (Pdb)
> 
> one more method as per example code :
> 
> (Pdb) dest_mac=stackIdObj.Field.find(FieldTypeId='ethernet.header.destinationAddress')
> 
> (Pdb) dest_mac.update(ValueType='increment', StartValue= '00:02:02:00:00:02', StepValue= '00:00:00:00:00:01', CountValue= 18) *** ixnetwork_restpy.errors.BadRequestError: InstanceId is not a string System.Exception: InstanceId is not a string at SDMCsLib.SDMObjIdPiece.GetIdAsString() at IxNetwork.Traffic2.Publishers.StackFieldHandler.Find(EnterExitSingleObjectHandler_EnterArgs args) at SDMHelpers.WalkContext.walkTo(SDMObjId objid, Hashtable idMapResponse, EnterReason reason) at SDMHelpers.SimplePublisher.Commit(ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitMessages, SDMSandbox track) at SDMCsLib.SDMPeer.commitPiece(ArrayList deltasForPublisher, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUnique) at SDMCsLib.SDMPeer.SANDBOX_DoCommit(Int32 eventMatch, ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUni que, eSandboxType sandboxType) at SDMCsLib.SDMSandbox.DoCommit(Boolean bCommitIfUnique, eSandboxType sandboxType) at SDMCsLib.RestService.SdmSandbox.Commit(Boolean isAddOperation) at SDMCsLib.RestService.SdmObject.Patch() at SDMCsLib.RestService.V1ObjectController.Patch(String path) Current Server Errors/Warnings: 01/23/2022 23:16:15 [WARNING] [Traffic Generate required] The Traffic Item was modified. Please perform a Traffic Generate to update the associated traffic Flow Groups (Pdb)

Hello,
It looks like we need to provide you a Hotfix patch for this, for that can you please provide your contact information, entitlement information, name/email to me directly at hasmik.shakaryan@keysight.com so I can open a support case.

Regards,
Hasmik

**Comment by hshakaryan** [comment]
Hello JensNeumannZAL , 

It looks like we need to provide you a Hotfix patch for this, for that can you please provide your contact information, entitlement information, name/email to me directly at [hasmik.shakaryan@keysight.com](mailto:hasmik.shakaryan@keysight.com) so I can open a support case.
 Regards, Hasmik



> Hello,
> 
> I have the same issue. I also did the same operation with the browser API and found a difference in the JSON string:
> 
> This is what the RestPy library sends. Interestingly, the "id" part is not explicitly added by my script but seems to be added internally. Also, contrary to what the server responds (`System.Exception: InstanceId is not a string`), it is actually a string as can be seen here clearly. `/api/v1/sessions/1/ixnetwork/traffic/trafficItem/1/configElement/1/stack/1/field` `{"trackingEnabled": true, "valueList": ["00:00:00:00:00:03"], "valueType": "valueList", "id": "1"}`
> 
> In the browser API it looks like this:
> 
> ```
> PATCH https://localhost:11009/api/v1/sessions/1/ixnetwork/traffic/trafficItem/1/configElement/1/stack/1/field/1
> content-type: text/plain; charset=utf-8
> 
> {
> 	"valueList": [
> 		"00:00:00:00:00:04"
> 	],
> 	"valueType": "valueList"
> }
> ```
> 
> As you can see, the `id` part does not even appear here.

Hello JensNeumannZAL , 

It looks like we need to provide you a Hotfix patch for this, for that can you please provide your contact information, entitlement information, name/email to me directly at [hasmik.shakaryan@keysight.com](mailto:hasmik.shakaryan@keysight.com) so I can open a support case.
 Regards, Hasmik

**Comment by hshakaryan** [comment]
Hello JensNeumannZAL , 

It looks like we need to provide you a Hotfix patch for this, for that can you please provide your contact information, entitlement information, name/email to me directly at [hasmik.shakaryan@keysight.com](mailto:hasmik.shakaryan@keysight.com) so I can open a support case.
 Regards, Hasmik

**Comment by dandelwa** [comment]
Hotfix is available on server end.
