### ISSUE TITLE
Not all vports find at first iteration of script

### ISSUE THREAD

**Issue by biepio** [OpenIxia/ixnetwork_restpy#63]
Hello,
I wrote bellow script:

import logging
from ixnetwork_restpy.testplatform.testplatform import TestPlatform

logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())

vports = ('access', 'uplink_r1', 'uplink_r2', 'uplink_r1_2')

test_platform = TestPlatform('10.10.0.222', rest_port=11101)
# test_platform.Trace = 'request_response'
test_platform.Trace = 'none'
ixnetwork = test_platform.Sessions.find().Ixnetwork

for v in vports:
    logger.info(f'Searching for vport: {v}')
    vport = ixnetwork.Vport.find(Name='^{}$'.format(v))
    logger.info(f'Found {len(vport)} vports')
    if len(vport) > 0:
        logger.info(f'Found: {vport[0]}')
    else:
        logger.info(f'Vport {v} not found')

When I do undermentioned steps:
1. restart IxNetwork session;
2. load my configuration file;
3. release all ports;
4. run script;
script always find only two ports at the first iteration. In the second one all ports are found. It is repetative behaviour.

I wonder what is wrong ? Could you help my with that ?
Thank you and best regards,
Piotr

[script_output.txt](https://github.com/OpenIxia/ixnetwork_restpy/files/8025446/script_output.txt)

**Comment by therkong** [comment]
Hi,  your script looks good.   In order to figure out the root cause,  can you send me the ixNet config file you're loading?
Also, what is your ixNetwork version and ixnetwork-restpy version?
You can send the config file to me at theresa.kong@keysight.com.   I'm part of automation tech support team.

**Comment by biepio** [comment]
Hello,
After upgraded our IXIA system to: IxNetwork 9.10update4, IxOS 9.10patch3 the issue was solved.
Thank you and best regards,
Piotr
