### ISSUE TITLE
How to change vlan_id

### ISSUE THREAD

**Issue by skayres** [OpenIxia/ixnetwork_restpy#8]
Hi!

IxNetwork version: 8.50.1501.9 EA

I can't find how to change VlanId. Only get_attribute is available.

```
ethernet_1 = device_group_1.Ethernet.add(UseVlans=UseVlans, VlanCount=VlanCount)
ethernet_1.Mac.Increment(start_value=start_mac, step_value='00:00:00:00:00:01')

# not work:
ethernet_1.Vlan.VlanId = '1,2,3,4,5')
# No increment on VLAN:
ethernet_1.Vlan.Increment(start_value=1, step_value=1)
# Can't set attribute
setattr(ethernet_1.Vlan, 'VlanId', '1 2 3 4 5')
setattr(ethernet_1.Vlan, 'vlanId', '1, 2, 3, 4, 5')
```

Couldn't you provide some info please.
![ixnetwork_restpy_vlanid_trouble](https://user-images.githubusercontent.com/10278524/63513326-89858400-c4ee-11e9-9685-33e7ad44d64b.PNG)

Thank you!

**Comment by ajbalogh** [comment]
The Vlan class encapsulates a system managed vlan node in the ixnetwork hierarchy.

	An instance of the class can be obtained by accessing the Vlan property from a parent instance.
	The internal properties list will be empty when the property is accessed and is populated from the server by using the **find** method.

```
ethernet_1 = device_group_1.Ethernet.add(UseVlans=UseVlans, VlanCount=VlanCount)
ethernet_1.Mac.Increment(start_value=start_mac, step_value='00:00:00:00:00:01')
vlan = ethernet_1.Vlan.find()
vlan.VlanId.Increment(start_value= '1', step_value='1'')
```
